# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='primer_apellido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='segundo_apellido',
            field=models.CharField(default='meetings', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consecionario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
